services:

  webapp:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '20080:80'

  sqlite:
    image: alpine
    command: sh -c "apk add --no-cache sqlite && sqlite3 /data/sqlite.db && tail -f /dev/null"
    volumes:
      - ./data:/data

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '26379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass nonsaferequiredpassword
    volumes: 
      - redis:/data

volumes:
  redis:
    driver: local
