services:

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis:/data

  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    links:
      - redis

  pub:
    build:
        dockerfile: docker/pub.dockerfile
    deploy:
      replicas: 2
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_TEST_CHANNEL=${REDIS_TEST_CHANNEL}
    links:
      - redis
      - sub

  sub:
    build:
        dockerfile: docker/sub.dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_TEST_CHANNEL=${REDIS_TEST_CHANNEL}
    links:
      - redis

volumes:
  redis:
    driver: local
